### PR TITLE
fix parse array with the external const correctly

### LINKED ISSUE #561: Panic on array parsing if length is externally defined
**Actual behavior** 

generating code for the following interface makes the tool to panic. 

(Note: math constant used just for convenience. Can be any other package-defined constant, not a hardcoded value)
```go
type Fooer interface {
    Foo([math.MaxInt8]string)
}
```
Output: `panic: interface conversion: ast.Expr is *ast.SelectorExpr, not *ast.BasicLit`

**Expected behavior**

Generate a mocked struct with a method that takes a `[127]string{}` (or `[math.MaxInt8]string{}`) array

**To Reproduce** Steps to reproduce the behavior
Explained in the "Actual behaviour" section

**Additional Information**

-   gomock mode (reflect or source): source
-   gomock version or git ref: v1.5.0
-   golang version: go version go1.15.8 darwin/amd64

~~**Triage Notes for the Maintainers**~~

### PR DESCRIPTION
**Pull request by sryoya**
Fixes #561 - Panic on array parsing if length is externally defined 

It also fixes the following minor problems in `TestParseArrayWithConstLength`, a test function related to this feature.
- It doesn't check all outputs to be asserted.
- It doesn't initialize some of the fields in `mockgen.fileParser`, even though they are initialized in the production code. (Actually, it caused an unnecessary test error by test data I added)

### CODE REVIEW

File: mockgen/parse.go [hunk 1]
```diff
@@ -409,8 +411,16 @@ func (p *fileParser) parseType(pkg string, typ ast.Expr) (model.Type, error) {
 			case (*ast.BasicLit):
 				value = val.Value
 			case (*ast.Ident):
-				// when the length is a const
+				// when the length is a const defined locally
 				value = val.Obj.Decl.(*ast.ValueSpec).Values[0].(*ast.BasicLit).Value
+			case (*ast.SelectorExpr):
+				// when the length is a const defined in an external package
+				usedPkg, err := importer.Default().Import(fmt.Sprintf("%s", val.X))
```
Comment (codyoss) [inline mockgen/parse.go:418]: nit: this error should be checked
nit: instead of `fmt.Sprintf("%s", val.X)` could you use val.X.Name

File: mockgen/parse.go [hunk 2]
```diff
@@ -409,8 +411,16 @@ func (p *fileParser) parseType(pkg string, typ ast.Expr) (model.Type, error) {
...
+				ev, err := types.Eval(token.NewFileSet(), usedPkg, token.NoPos, val.Sel.String())
```
Comment (codyoss) [inline mockgen/parse.go:419]: nit: please use `val.Sel.Name`

**Review by codyoss — CHANGES_REQUESTED** [review]
Thanks for the contribution, just a couple of minor nits.

File: mockgen/parse.go (hunk 1 above)
Comment (sryoya) [reply mockgen/parse.go:418]: > nit: this error should be checked

Thanks for the catch! I missed this error.
https://github.com/golang/mock/pull/569/commits/d272a9382fc5b18efa25a2caa70b85b80435b839

> nit: instead of fmt.Sprintf("%s", val.X) could you use val.X.Name

The `X` field in the `SelectorExpr` type doesn't seem to have "Name" as its type is just the `Expr` interface.
https://github.com/golang/mock/pull/569/files

File: mockgen/parse.go (hunk 2 above)
Comment (sryoya) [reply mockgen/parse.go]: Ok!

https://github.com/golang/mock/commit/d272a9382fc5b18efa25a2caa70b85b80435b839

**Comment by sryoya** [comment]
Thanks for the review 🌵 I've either fixed or replied to your comments.

File: mockgen/parse.go (hunk 1 above)
Comment (codyoss) [reply mockgen/parse.go:418]: Sorry I should have been more clear, you are right. To get at name you must cast it. val.X should always be an identifier in this case so `val.X.(*ast.Ident).Name` should work. But this is good to, less panic prone should ast representation change I suppose.

**Review by codyoss — APPROVED** [review]
LGTM

**Comment by codyoss** [comment]
@sryoya Thank you for your contribution! 🎆

File: mockgen/parse.go (hunk 1 above)
Comment (sryoya) [reply mockgen/parse.go:418]: Ah, I see. Your way looks fine too, but I feel using `fmt.Sprintf` is less panic prone as you say.
Thanks for the clarification 😄
