### PR TITLE
fix generates non-compilable code

### LINKED ISSUE #370: Generates non-compilable code
I only need to document one specific parameter in the interface, an example:
```
Search(_ Ctx, _ Auth, query string,_ Lang,_ Page)
```

**Actual behavior** Generates non-compilable code, sample:

```
(m *MockSearcher) TrackByIDs(_ Ctx, _ UserID, subsUserIDs []UserID, _ []ulid.ULID) ([]TrackInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackByIDs", _, _, subsUserIDs, _)
	ret0, _ := ret[0].([]TrackInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
```

**Expected behavior** I expected to see that result.
```
(m *MockSearcher) TrackByIDs(arg1 Ctx, arg2 UserID, subsUserIDs []UserID, arg4 []ulid.ULID) ([]TrackInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackByIDs", _, _, subsUserIDs, _)
	ret0, _ := ret[0].([]TrackInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
```

**To Reproduce** Steps to reproduce the behavior

1.  Write interface:
```
type Sample interface {
	Test(val int, _ string) 
}
```
2.  Generate mock.

**Additional Information**

-   gomock version or git ref: 1.3.1 
-   golang version: 1.13

### PR DESCRIPTION
**Pull request by ZergsLaw**
Fixes #370 .

**Description**
- [x] fixed bug

**Submitter Checklist**

- [x] Includes tests

### CODE REVIEW

**Comment by ZergsLaw** [comment]
@googlebot I signed it!

File: mockgen/mockgen_test.go [hunk 1]
```diff
@@ -267,3 +267,89 @@ func findMethod(t *testing.T, identifier, methodName string, lines []string) int
...
+				},
+			},
+			expected: []string{"firstArg", "arg1"},
+		},
+	} {
+		t.Run(testCase.name, func(t *testing.T) {
+			g := generator{}
+
+			result := g.getArgNames(testCase.method)
+			if !testEqSliceStr(t, result, testCase.expected) {
```
Comment (codyoss) [inline mockgen/mockgen_test.go]: I would recommend using `reflect.DeepEquals` here, but it seems like we have a name collision in that package. I will refactor this later

**Comment by codyoss** [comment]
Thank you for your contribution! 🎆

File: mockgen/mockgen_test.go (hunk 1 above)
Comment (ZergsLaw) [reply mockgen/mockgen_test.go]: Yes, that's what I planned initially, but since there was a conflict of names, I decided not to touch upon it at the moment.
