### PR TITLE
gomock: documents exported functions

### LINKED ISSUE #222: Document exported methods
A number of exported methods are undocumented, and therefore their behaviour can only be discovered by reading their code. For example, `Controller.Finish()` can only be called once, otherwise the test will fail, but this is not documented anywhere.

### PR DESCRIPTION
**Pull request by poy**
fixes #222

### CODE REVIEW

File: gomock/controller.go [hunk 1]
```diff
@@ -92,6 +113,8 @@ type Controller struct {
 	finished      bool
 }
 
+// NewController a new Controller. It is the preferred way to create a
```
Comment (balshetzer) [inline gomock/controller.go]: Is this missing a word? NewController creates a new Controller.

Comment (poy) [reply gomock/controller.go]: Ah, thanks. I think it should be:

> NewController returns a new Controller.

File: gomock/controller.go [hunk 2]
```diff
@@ -200,6 +226,8 @@ func (ctrl *Controller) Call(receiver interface{}, method string, args ...interf
 	return rets
 }
 
+// Finish checks to see if all the methods that were expected to be called
+// were called. It should be invoked for each Controller.
```
Comment (RJPercival) [inline gomock/controller.go]: It'd be good to document the requirement that it only be invoked exactly once.
