### PR TITLE
Fix #71 Do signature change error msg

### LINKED ISSUE #71: Hard to debug when a Do(fn) function no longer matches its mock signature
Situation: we had code like:
```go
type Foo interface {
  Bar(arg1, arg2 string)
  ...
}
```
and tests like:
```go
do := func(arg1, arg2 string) { ... }
// ... bunch of code ...
myBarMock.EXPECT().Bar(wantArg1, wantArg2).Do(do)
```

Then we added an argument to `Bar`:
```go
type Foo interface {
  Bar(arg1, arg2, arg3 string)
  ...
}
```
and updated the `EXPECT()`:
```go
do := func(arg1, arg2 string) { ... }
// ... bunch of code ...
myBarMock.EXPECT().Bar(wantArg1, wantArg2, wantArg3).Do(do)
```
... but forgot to update `do`. The result was "panic: reflect: Call with too many input arguments" with no strong indication that what was wrong was the `do` function, rather than some place where the third argument hadn't been added (e.g. missing `wantArg3`).
It would be nice if the message said something more obvious like "EXPECT.()Do() function doesn't match the mock signature".

### PR DESCRIPTION
**Pull request by cvgw**
Fixes #71 

**Description**

Update the error handling for Call.Do and Call.DoAndReturn in the case where
the argument passed does not match expectations.

* panic if the argument is not a function
* panic if the number of input arguments do not match those expected by Call
* panic if the types of the input arguments do not match those expected
by Call

Call.DoAndReturn has additional validations on the return signature

* panic if the number of return arguments do not match those expected by
Call
* panic if the types of return arguments do not match those expected by
Call

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes tests

**Reviewer Notes**

- [ ] The code flow looks good.
- [ ] Tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
- Update validations for Do + DoAndReturn; now panics when argument passed to Do is not a function or does not match the signature of the mocked function
```

### CODE REVIEW

**Comment by cvgw** [comment]
Open question about this PR:
Should we verify the return args? Should we verify them for both `Do` and `DoAndReturn`?

File: gomock/call_test.go [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package gomock
 
 import (
+	"reflect"
```
Comment (codyoss) [inline gomock/call_test.go]: Could you add the copyright to this file. Eventually we need to go and get all the files caught up.

**Comment by cvgw** [comment]
I did some brief testing and found that gomock currently allows arguments to `Do` which do not match the return signature of the mocked method. I don't think we should start validating that as it will be a break change so I'm going to revert that.

However, gomock raises an obscure error when arguments to `DoAndReturn` do not match the return signature of the mocked method. So I will keep the additional validation there.

File: gomock/internal/validate/validate.go [hunk 2]
```diff
@@ -0,0 +1,201 @@
...
+			"expected function to have %d return vals not %d",
+			expectedFunc.NumOut(), actualFunc.NumOut())
+	}
+
+	for i := 0; i < expectedFunc.NumOut(); i++ {
+		expectedArg := expectedFunc.Out(i)
+		actualArg := actualFunc.Out(i)
+
+		if err := arg(actualArg, expectedArg); err != nil {
+			return errors.Wrapf(err, "return argument at %d", i)
```
Comment (codyoss) [inline gomock/internal/validate/validate.go]: Do we need to wrap the errors? Could we append the old error as details? Or if we do want to wrap maybe we should consider `https://github.com/golang/xerrors/` instead as that is the api in go1.13. Thoughts?

Comment (cvgw) [reply gomock/internal/validate/validate.go]: I don't think it's necessary to wrap them; I actually did it out of habit and raised the same question in chat. I recently read a great posts about how the errors you return are part of your public API, wrapping errors expands the surface of that API.

I'm happy to go with whatever you prefer.

Comment (codyoss) [reply gomock/internal/validate/validate.go]: I would say for now let just not wrap since there is not a strong case for it. This has the benefit of pushing one less dependency on our users too.

Comment (cvgw) [reply gomock/internal/validate/validate.go]: Done

File: gomock/call.go [hunk 3]
```diff
@@ -106,9 +108,20 @@ func (c *Call) MaxTimes(n int) *Call {
...
+	switch v.Kind() {
+	case reflect.Func:
+		mt := c.methodType
+
+		ft := v.Type()
+		if err := validate.InputAndOutputSig(ft, mt); err != nil {
+			panic(fmt.Sprintf("DoAndReturn: %s", err))
+		}
+	default:
+		panic("DoAndReturn: argument must be a function")
```
Comment (codyoss) [inline gomock/call.go]: Since we are now explicitly panicing I think we should update the doc string.

File: gomock/internal/validate/validate.go [hunk 4]
```diff
@@ -0,0 +1,199 @@
...
+			return false
+		}
+
+	}
+
+	return true
+}
+
+func interfaceArg(actualArg, expectedArg reflect.Type) error {
+	if !actualArg.ConvertibleTo(expectedArg) {
```
Comment (codyoss) [inline gomock/internal/validate/validate.go]: Honest question: Does this cover the implements?

File: gomock/call.go (hunk 3 above)
Comment (cvgw) [reply gomock/call.go]: Updated

File: gomock/internal/validate/validate.go (hunk 4 above)
Comment (cvgw) [reply gomock/internal/validate/validate.go]: Yes it does, if expectedArg is something like `Stringer` and `actualArg` is an instance of some type `Foo` which implements `Stringer` this line will evaluate to true.

Comment (cvgw) [reply gomock/internal/validate/validate.go]: I added another test case to make that more clear

**Comment by codyoss** [comment]
I was just reading over this issue. Made me question if we should be using panics at all. https://github.com/golang/mock/issues/158#issuecomment-378720709 

This PR is just making panics in this case more explicit. I wonder in the future if we should recover all of them and t.Fatal with the TestReporter  we should have access to in the controller.

**Comment by cvgw** [comment]
> I was just reading over this issue. Made me question if we should be using panics at all. [#158 (comment)](https://github.com/golang/mock/issues/158#issuecomment-378720709)
> 
> This PR is just making panics in this case more explicit. I wonder in the future if we should recover all of them and t.Fatal with the TestReporter we should have access to in the controller.

I think that is totally valid but brings up back to the question of what to do for code executing outside of the main goroutine where we can't call `t.Fatal`. We should brainstorm about it some more.

**Comment by horejsek** [comment]
BTW this change was released as 1.4.2, changing only minor version. It breaks the current code. I think it should be released at least as 1.5.0.

**Comment by Linus-Boehm** [comment]
Can confirm that this is a breaking change. Gomock now interprets pointers wrong and wants a string:

Signature of func:

` Save(config *repo.Config, namespace domain.NS)`

Error:

`panic: DoAndReturn: input argument at 1: expected arg of kind string not interface`

**Comment by codyoss** [comment]
Thank you for bring this up, that behavior was not intentional. Can you please provide a small example of code this breaks so we can add a better test.

**Comment by horejsek** [comment]
```go
mock.EXPECT().Foo(gomock.Any()).DoAndReturn(func(...interface{}) error {return nil})
```

We didn't care about parameters so we left `...interface{}` there which was OK and now it's panicing. The change was easy thought, just use real type instead.

**Comment by codyoss** [comment]
@Linus-Boehm was this a similar use case for you. I will be reverting for now and creating a new tag 1.4.3 until I have more time to evaluate how we want to move forward this this.

**Comment by codyoss** [comment]
New release with the change reverted: [v1.4.3](https://github.com/golang/mock/releases/tag/v1.4.3)

**Comment by Linus-Boehm** [comment]
`mock.EXPECT().Foo("some-expected-string").DoAndReturn(func(name interface{}) error {return nil})`

It panics becuase "some-expected-string" is not an interface, so yeah that should be the same reason.

**Comment by cvgw** [comment]
> `mock.EXPECT().Foo("some-expected-string").DoAndReturn(func(name interface{}) error {return nil})`
> 
> It panics becuase "some-expected-string" is not an interface, so yeah that should be the same reason.

@Linus-Boehm for clarity, what is the signature of method `Foo` on the type being mocked?
