### PR TITLE
Test helper in mock

### LINKED ISSUE #239: mocks should call t.Helper()
The mocks are being flagged as a failing line during a test failure. This is due to the fact that `Controller.Call()`. invokes `t.Helper()`, but the mock does not. This means that instead of the offending line being called out, the mock is.

This could be solved by having the mock also call `t.Helper()`.

### PR DESCRIPTION
**Pull request by poy**
fixes #239

### CODE REVIEW

File: gomock/controller.go [hunk 1]
```diff
@@ -70,62 +70,84 @@ type TestReporter interface {
...
+	Helper()
+}
+
 // A Controller represents the top-level control of a mock ecosystem.
 // It defines the scope and lifetime of mock objects, as well as their expectations.
 // It is safe to call Controller's methods from multiple goroutines.
 type Controller struct {
 	mu            sync.Mutex
-	t             TestReporter
+	T             TestHelper
```
Comment (balshetzer) [inline gomock/controller.go]: I don't love that T is now a public var. I understand that it needs to be accessed by the mock. It's unfortunate that the testing package API requires direct access to T for T.Helper. I think we should at least add a comment that T is only public so that the mock can use it and any attempt by the user to set it, modify it, call it, etc. is unsupported and could be broken in the future without any consideration for backward compatibility (or something like that).

I wish T.Helper took a number like most other call stack related functions.

File: gomock/controller.go [hunk 2]
```diff
@@ -70,62 +70,84 @@ type TestReporter interface {
...
-	r.t.Fatalf(format, args...)
+	r.TestHelper.Fatalf(format, args...)
 }
 
 // WithContext returns a new Controller and a Context, which is cancelled on any
 // fatal failure.
 func WithContext(ctx context.Context, t TestReporter) (*Controller, context.Context) {
+	h, ok := t.(TestHelper)
+	if !ok {
+		// TODO
```
Comment (balshetzer) [inline gomock/controller.go]: Do now?

File: gomock/controller.go (hunk 1 above)
Comment (poy) [reply gomock/controller.go]: I will add a comment. I agree it is unfortunate, but I was unable to think of a way around it.

File: gomock/controller.go (hunk 2 above)
Comment (poy) [reply gomock/controller.go]: Ah, missed that one. Thanks.

**Comment by poy** [comment]
@balshetzer PTAL

**Comment by poy** [comment]
@balshetzer PTAL

File: gomock/controller.go [hunk 3]
```diff
@@ -70,62 +70,88 @@ type TestReporter interface {
...
 	defer r.cancel()
-	r.t.Fatalf(format, args...)
+	r.TestHelper.Fatalf(format, args...)
 }
 
 // WithContext returns a new Controller and a Context, which is cancelled on any
 // fatal failure.
 func WithContext(ctx context.Context, t TestReporter) (*Controller, context.Context) {
+	h, ok := t.(TestHelper)
+	if ok {
```
Comment (balshetzer) [inline gomock/controller.go]: if !ok {

**Comment by poy** [comment]
@balshetzer PTAL

**Comment by mikhailkolesnik** [comment]
can you pease tag this version. When we use `go get ` to install mockgen and `dep` to install `github.com/golang/mock` dep thinks that 1.1.1 is the most recent version and mockgen generates code that is not compatible with it.

**Comment by poy** [comment]
@mikhailkolesnik tagged v1.2.0
